"""Add Column expires-at to user-sessions

Revision ID: c41903d1e4b5
Revises: 28e2d54f3621
Create Date: 2025-06-04 14:39:48.485418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c41903d1e4b5'
down_revision: Union[str, None] = '28e2d54f3621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('expires_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_sessions', 'expires_at')
    # ### end Alembic commands ###
